### ISSUE TITLE
new juke firmware broke the integration

### ISSUE THREAD

**Issue by gholevas** [pkarimov/jukeaudio_ha#8]
Hopefully it is an easy fix to support the new juke firmware (release-4.2.2-8) because I was really enjoying this integration :)

**Comment by pkarimov** [comment]
Hey @gholevas I am starting to look at this. It certainly seems they introduced a new API version but in a way that breaks the previous versions :(. Let me know what problems you are seeing - this way I won't rely on just my own observations.

**Comment by pkarimov** [comment]
@gholevas This is now fixed in that the integration should work with the latest update. However, I have not yet added any real support for the major things Juke introduced in this release. That's the next thing to tackle.
